site_name: 'DQM4HEP'

pages:
  - Home: 'index.md'
  - Download: 'download.md'
  - User Manual:
    - Core tools: 'user-manual/core-tools.md'
    - The plugin system: 'user-manual/plugin-system.md'
    - Event streaming: 'user-manual/event-streaming.md'
    - Quality tests: 'user-manual/quality-test.md'
    - Networking: 'user-manual/networking.md'
  - References: 'references.md'
  - About:
    - Licence: 'about/licence.md'
    - Contact: 'about/contact.md'
    - Contribute: 'about/contribute.md'

# theme: mkdocs
theme_dir: cinder

extra_css:
  - stylesheet.css