site_name: 'DQM4HEP'

pages:
  - Home: 'index.md'
  - Download: 'download.md'
  - User Manual:
    - Core tools: 'user-manual/core-tools.md'
  # - Manual:
    # - Installation guide: 'manual/install.md'
    # - User guide: 'manual/userguide.md'
    # - Developer guide: 'manual/devguide.md'
  - References: 'references.md'
  - About:
    - Licence: 'about/licence.md'
    - Contact: 'about/contact.md'
    - Contribute: 'about/contribute.md'

# theme: mkdocs
theme_dir: cinder
